---
title: "RAM Data Visualization"
output:
  html_document:
    toc: yes
    toc_depth: 2
---

```{r render-site, include=FALSE,eval=F}
library(rmarkdown)
library(bookdown)

#might need to remake docs/ everytime?
#knit this then commit and push

#render homelink
# rmarkdown::render("homelink.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/code/homelink")

#render darksidea
rmarkdown::render("code/Darksidea.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_darksidea")
rmarkdown::render("code/Darksidea.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_darksidea_noEDGEnoMP")
rmarkdown::render("code/Darksidea_allSamplesincEDGE.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_darksidea_allSamplesincEDGE")



#render Taxonomy
rmarkdown::render("code/3_KSU_TaxaPlots_kf.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_taxonomy")

#render ordinations
rmarkdown::render("code/5_KSU_CommunityOrdinations_kf.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_ordinations")

#render Rudgers2021 comparison
rmarkdown::render("code/Comparison_Rudgers2021.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_Comparison_Rudgers2021")

#render nestedness
rmarkdown::render("code/nestedness.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_nestedness")
rmarkdown::render("code/nestedness_clusters_v2.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_nestedness_clusters")

#render explanatory var
rmarkdown::render("code/ExplanatoryVariables.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_explanatoryVariables")

#render spe gen
rmarkdown::render("code/2_KSU_OTUdownselection.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_generalist_v_specialist")

#render InterkingdomRegressions
rmarkdown::render("code/InterkingdomRegressions.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_InterkingdomRegressions")

#render DriversOfFungalCommunities
rmarkdown::render("code/DriversOfFungalCommunities.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_DriversOfFungalCommunities3")

#render PAM_Clusters
rmarkdown::render("code/PAM_Clusters.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_PAM_Clusters")

#render BacterialFungalClusterInteractions
rmarkdown::render("code/BacterialFungalClusterInteractions.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_BacterialFungal_Cluster_Interactions")

#render SFAFposter
rmarkdown::render("code/SFAFposter.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_SFAFposter")

#render ManuscriptOrganizing
rmarkdown::render("code/ManuscriptOrganizing.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_ManuscriptOrganizing")

#render ManuscriptOrganizing
rmarkdown::render("code/ManuscriptOrganizing.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_ManuscriptOrganizing")


#render AlphaBetaGamma_BySite
rmarkdown::render("code/AlphaBetaGamma_BySite.Rmd", output_file="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/github_AlphaBetaGamma_BySite")

```

\

<a href="github_darksidea.html" target="_blank">Darksidea stats for Aaron</a>

\
\
<a href="github_Comparison_Rudgers2021.html" target="_blank">Comparison</a> to previous manuscript (Rudgers, J.A., Fox, S., Porras‐Alfaro, A., Herrera, J., Reazin, C., Kent, D.R., Souza, L., Chung, Y.A., & Jumpponen, A. (2022). Biogeography of root‐associated fungi in foundation grasses of North American plains. Journal of Biogeography, 49(1), 22-37. doi/10.1111/jbi.14260)\
<object data="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/JournalofBiogeography2021_Rudgers_BiogeographyOfRootAssociatedFungiInFoundationGrassesOfNorthAmericanPlains.pdf" type="application/pdf" width="100%" height="500px">

<p>Unable to display PDF file. <a href="/Users/L347123/Desktop/ksu-paired-amplicon-workflow/docs/JournalofBiogeography2021_Rudgers_BiogeographyOfRootAssociatedFungiInFoundationGrassesOfNorthAmericanPlains.pdf">Download</a> instead (whether the PDF displays depends on your browser).</p>

</object>

\
\
\

## RAM paired amplicons taxa of interest queries {.unnumbered}

### Distribution and diversity of *Darksidea* and *Monosporascus* sp. with variable input data {.unnumbered}

-   <a href="github_darksidea_noEDGEnoMP.html" target="_blank">[Standard input data:]{.underline} EDGE samples excluded, samples with missing pairs excluded (last updated 21 July 2024)</a>

-   <a href="github_darksidea_allSamplesincEDGE.html" target="_blank">Full untrimmed input data: [all samples]{.underline}; EDGE samples included, samples with missing pairs included (last updated 21 July 2024)</a>

    -   changes: increased n of samples from 484 to 654, n SEV samples increased from 10 to 53, *Monosporascus* detectedat the SEV (1 OTU found in 2.7% of *Black grama* SEV soils with mean relative abundance of 1.9%, when present)

\
\
\

## Pulling story elements for manuscript {.unnumbered}

\

-   <a href="github_explanatoryVariables.html" target="_blank">Environmental/metadata processing and summary stats (last updated 10 July 2024)</a>

-   <a href="github_AlphaBetaGamma_BySite.html" target="_blank">Alpha- Beta- Gamma- diversity by site (last updated 22 July 2024)</a>

\
\

## Bulk Analyses {.unnumbered}

\

### New/Corrected Analyses {.unnumbered}

\

-   <a href="1_KSU_16S_ITS_otu_processing_kf_EXAMPLE.html" target="_blank">Raw OTU table processing (last updated 11 July 2024)</a>

-   <a href="github_DriversOfFungalCommunities3.html" target="_blank">Drivers Of Fungal Community Dynamics (last updated 07 July 2024)</a>

\

### Analyses with metadata not yet fixed {.unnumbered}

\*Error in metadata: Site ONF should have GPS coordinates of 34.80954, -94.13184 instead of 3[9]{style="color:red;"}.80954, -94.13184\
\

-   <a href="/github_BacterialFungal_Cluster_Interactions.html" target="_blank">~~Relationships Among Bacterial and Fungal Clusters (newest, last updated 12 May 2024)~~</a>

-   <a href="github_PAM_Clusters.html" target="_blank">PAM Clustering (now has Bacteria, last updated 12 May 2024)</a>

-   <a href="github_DriversOfFungalCommunities2.html" target="_blank">Drivers Of Fungal Community Dynamics</a>

-   <a href="github_InterkingdomRegressions.html" target="_blank">Inter-kingdom Regressions</a>

-   <a href="github_generalist_v_specialist.html" target="_blank">Generalist vs. Specialist (OTU down-selection)</a>

-   <a href="github_nestedness.html" target="_blank">Nestedness vs turnover</a>

-   $\beta_{NULL}$-diversity modeling

-   ordinations & permANOVA
